// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /a/zoha-vte-rs/gir-files
// from /a/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }
}
