// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/milan/git/zoha-vte-rs/gir-files
// from /home/milan/git/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct EventContext(Boxed<ffi::VteEventContext>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::vte_event_context_get_type(), ptr as *mut _) as *mut ffi::VteEventContext,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::vte_event_context_get_type(), ptr as *mut _),
        type_ => || ffi::vte_event_context_get_type(),
    }
}

impl EventContext {
    #[doc(alias = "vte_event_context_get_event")]
    #[doc(alias = "get_event")]
    pub fn event(&self) -> Option<gdk::Event> {
        unsafe { from_glib_none(ffi::vte_event_context_get_event(self.to_glib_none().0)) }
    }
}
