// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/milan/git/zoha-vte-rs/gir-files
// from /home/milan/git/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

use crate::ffi;
use glib::{bitflags::bitflags, prelude::*, translate::*};

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VteFeatureFlags")]
    pub struct FeatureFlags: u32 {
        #[doc(alias = "VTE_FEATURE_FLAG_BIDI")]
        const FLAG_BIDI = ffi::VTE_FEATURE_FLAG_BIDI as _;
        #[doc(alias = "VTE_FEATURE_FLAG_ICU")]
        const FLAG_ICU = ffi::VTE_FEATURE_FLAG_ICU as _;
        #[doc(alias = "VTE_FEATURE_FLAG_SYSTEMD")]
        const FLAG_SYSTEMD = ffi::VTE_FEATURE_FLAG_SYSTEMD as _;
        #[doc(alias = "VTE_FEATURE_FLAG_SIXEL")]
        const FLAG_SIXEL = ffi::VTE_FEATURE_FLAG_SIXEL as _;
        #[doc(alias = "VTE_FEATURE_FLAGS_MASK")]
        const FLAGS_MASK = ffi::VTE_FEATURE_FLAGS_MASK as _;
    }
}

#[doc(hidden)]
impl IntoGlib for FeatureFlags {
    type GlibType = ffi::VteFeatureFlags;

    #[inline]
    fn into_glib(self) -> ffi::VteFeatureFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::VteFeatureFlags> for FeatureFlags {
    #[inline]
    unsafe fn from_glib(value: ffi::VteFeatureFlags) -> Self {
        Self::from_bits_truncate(value)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VtePropertyFlags")]
    pub struct PropertyFlags: u32 {
        #[doc(alias = "VTE_PROPERTY_FLAG_NONE")]
        const NONE = ffi::VTE_PROPERTY_FLAG_NONE as _;
        #[doc(alias = "VTE_PROPERTY_FLAG_EPHEMERAL")]
        const EPHEMERAL = ffi::VTE_PROPERTY_FLAG_EPHEMERAL as _;
    }
}

#[doc(hidden)]
impl IntoGlib for PropertyFlags {
    type GlibType = ffi::VtePropertyFlags;

    #[inline]
    fn into_glib(self) -> ffi::VtePropertyFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::VtePropertyFlags> for PropertyFlags {
    #[inline]
    unsafe fn from_glib(value: ffi::VtePropertyFlags) -> Self {
        Self::from_bits_truncate(value)
    }
}

impl StaticType for PropertyFlags {
    #[inline]
    #[doc(alias = "vte_property_flags_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::vte_property_flags_get_type()) }
    }
}

impl glib::HasParamSpec for PropertyFlags {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for PropertyFlags {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for PropertyFlags {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for PropertyFlags {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<PropertyFlags> for glib::Value {
    #[inline]
    fn from(v: PropertyFlags) -> Self {
        ToValue::to_value(&v)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VtePtyFlags")]
    pub struct PtyFlags: u32 {
        #[doc(alias = "VTE_PTY_NO_LASTLOG")]
        const NO_LASTLOG = ffi::VTE_PTY_NO_LASTLOG as _;
        #[doc(alias = "VTE_PTY_NO_UTMP")]
        const NO_UTMP = ffi::VTE_PTY_NO_UTMP as _;
        #[doc(alias = "VTE_PTY_NO_WTMP")]
        const NO_WTMP = ffi::VTE_PTY_NO_WTMP as _;
        #[doc(alias = "VTE_PTY_NO_HELPER")]
        const NO_HELPER = ffi::VTE_PTY_NO_HELPER as _;
        #[doc(alias = "VTE_PTY_NO_FALLBACK")]
        const NO_FALLBACK = ffi::VTE_PTY_NO_FALLBACK as _;
        #[doc(alias = "VTE_PTY_NO_SESSION")]
        const NO_SESSION = ffi::VTE_PTY_NO_SESSION as _;
        #[doc(alias = "VTE_PTY_NO_CTTY")]
        const NO_CTTY = ffi::VTE_PTY_NO_CTTY as _;
        #[doc(alias = "VTE_PTY_DEFAULT")]
        const DEFAULT = ffi::VTE_PTY_DEFAULT as _;
    }
}

#[doc(hidden)]
impl IntoGlib for PtyFlags {
    type GlibType = ffi::VtePtyFlags;

    #[inline]
    fn into_glib(self) -> ffi::VtePtyFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::VtePtyFlags> for PtyFlags {
    #[inline]
    unsafe fn from_glib(value: ffi::VtePtyFlags) -> Self {
        Self::from_bits_truncate(value)
    }
}

impl StaticType for PtyFlags {
    #[inline]
    #[doc(alias = "vte_pty_flags_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::vte_pty_flags_get_type()) }
    }
}

impl glib::HasParamSpec for PtyFlags {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for PtyFlags {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for PtyFlags {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for PtyFlags {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<PtyFlags> for glib::Value {
    #[inline]
    fn from(v: PtyFlags) -> Self {
        ToValue::to_value(&v)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VteUuidFormat")]
    pub struct UuidFormat: u32 {
        #[doc(alias = "VTE_UUID_FORMAT_SIMPLE")]
        const SIMPLE = ffi::VTE_UUID_FORMAT_SIMPLE as _;
        #[doc(alias = "VTE_UUID_FORMAT_BRACED")]
        const BRACED = ffi::VTE_UUID_FORMAT_BRACED as _;
        #[doc(alias = "VTE_UUID_FORMAT_URN")]
        const URN = ffi::VTE_UUID_FORMAT_URN as _;
        #[doc(alias = "VTE_UUID_FORMAT_ANY")]
        const ANY = ffi::VTE_UUID_FORMAT_ANY as _;
        #[doc(alias = "VTE_UUID_FORMAT_ID128")]
        const ID128 = ffi::VTE_UUID_FORMAT_ID128 as _;
        #[doc(alias = "VTE_UUID_FORMAT_ANY_ID128")]
        const ANY_ID128 = ffi::VTE_UUID_FORMAT_ANY_ID128 as _;
    }
}

#[doc(hidden)]
impl IntoGlib for UuidFormat {
    type GlibType = ffi::VteUuidFormat;

    #[inline]
    fn into_glib(self) -> ffi::VteUuidFormat {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::VteUuidFormat> for UuidFormat {
    #[inline]
    unsafe fn from_glib(value: ffi::VteUuidFormat) -> Self {
        Self::from_bits_truncate(value)
    }
}

impl StaticType for UuidFormat {
    #[inline]
    #[doc(alias = "vte_uuid_format_get_type")]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::vte_uuid_format_get_type()) }
    }
}

impl glib::HasParamSpec for UuidFormat {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        Self::ParamSpec::builder
    }
}

impl glib::value::ValueType for UuidFormat {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for UuidFormat {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        unsafe { from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0)) }
    }
}

impl ToValue for UuidFormat {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<UuidFormat> for glib::Value {
    #[inline]
    fn from(v: UuidFormat) -> Self {
        ToValue::to_value(&v)
    }
}
