// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{bitflags::bitflags,prelude::*,translate::*};
use std::{fmt};
use zoha_vte_sys::*;

#[cfg(feature = "v0_62")]
bitflags! {
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_62")))]
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VteFeatureFlags")]
    pub struct FeatureFlags: u32 {
        #[doc(alias = "VTE_FEATURE_FLAG_BIDI")]
        const FLAG_BIDI = VTE_FEATURE_FLAG_BIDI as _;
        #[doc(alias = "VTE_FEATURE_FLAG_ICU")]
        const FLAG_ICU = VTE_FEATURE_FLAG_ICU as _;
        #[doc(alias = "VTE_FEATURE_FLAG_SYSTEMD")]
        const FLAG_SYSTEMD = VTE_FEATURE_FLAG_SYSTEMD as _;
        #[doc(alias = "VTE_FEATURE_FLAG_SIXEL")]
        const FLAG_SIXEL = VTE_FEATURE_FLAG_SIXEL as _;
        #[doc(alias = "VTE_FEATURE_FLAGS_MASK")]
        const FLAGS_MASK = VTE_FEATURE_FLAGS_MASK as _;
    }
}

#[cfg(feature = "v0_62")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_62")))]
impl fmt::Display for FeatureFlags {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[cfg(feature = "v0_62")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_62")))]
#[doc(hidden)]
impl IntoGlib for FeatureFlags {
    type GlibType = VteFeatureFlags;

    #[inline]
    fn into_glib(self) -> VteFeatureFlags {
        self.bits()
    }
}

#[cfg(feature = "v0_62")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_62")))]
#[doc(hidden)]
impl FromGlib<VteFeatureFlags> for FeatureFlags {
    #[inline]
    unsafe fn from_glib(value: VteFeatureFlags) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "VtePtyFlags")]
    pub struct PtyFlags: u32 {
        #[doc(alias = "VTE_PTY_NO_LASTLOG")]
        const NO_LASTLOG = VTE_PTY_NO_LASTLOG as _;
        #[doc(alias = "VTE_PTY_NO_UTMP")]
        const NO_UTMP = VTE_PTY_NO_UTMP as _;
        #[doc(alias = "VTE_PTY_NO_WTMP")]
        const NO_WTMP = VTE_PTY_NO_WTMP as _;
        #[doc(alias = "VTE_PTY_NO_HELPER")]
        const NO_HELPER = VTE_PTY_NO_HELPER as _;
        #[doc(alias = "VTE_PTY_NO_FALLBACK")]
        const NO_FALLBACK = VTE_PTY_NO_FALLBACK as _;
        #[doc(alias = "VTE_PTY_NO_SESSION")]
        const NO_SESSION = VTE_PTY_NO_SESSION as _;
        #[doc(alias = "VTE_PTY_NO_CTTY")]
        const NO_CTTY = VTE_PTY_NO_CTTY as _;
        #[doc(alias = "VTE_PTY_DEFAULT")]
        const DEFAULT = VTE_PTY_DEFAULT as _;
    }
}

impl fmt::Display for PtyFlags {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[doc(hidden)]
impl IntoGlib for PtyFlags {
    type GlibType = VtePtyFlags;

    #[inline]
    fn into_glib(self) -> VtePtyFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<VtePtyFlags> for PtyFlags {
    #[inline]
    unsafe fn from_glib(value: VtePtyFlags) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for PtyFlags {
    #[inline]
    fn static_type() -> glib::Type {
        unsafe { from_glib(vte_pty_flags_get_type()) }
    }
}

impl glib::HasParamSpec for PtyFlags {
                type ParamSpec = glib::ParamSpecFlags;
                type SetValue = Self;
                type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;
    
                fn param_spec_builder() -> Self::BuilderFn {
                    |name| Self::ParamSpec::builder(name)
                }
}

impl glib::value::ValueType for PtyFlags {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for PtyFlags {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for PtyFlags {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<PtyFlags> for glib::Value {
    #[inline]
    fn from(v: PtyFlags) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

