// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

mod pty;
pub use self::pty::Pty;

mod terminal;
pub use self::terminal::Terminal;

mod regex;
pub use self::regex::Regex;

mod enums;
pub use self::enums::CursorBlinkMode;
pub use self::enums::CursorShape;
pub use self::enums::EraseBinding;
#[cfg(feature = "v0_50")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_50")))]
pub use self::enums::Format;
pub use self::enums::PtyError;
#[cfg(feature = "v0_46")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_46")))]
pub use self::enums::RegexError;
#[cfg(feature = "v0_52")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_52")))]
pub use self::enums::TextBlinkMode;
pub use self::enums::WriteFlags;

mod flags;
#[cfg(feature = "v0_62")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_62")))]
pub use self::flags::FeatureFlags;
pub use self::flags::PtyFlags;

pub mod traits {
    pub use super::terminal::TerminalExt;
}
