// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/milan/git/zoha-vte-rs/gir-files
// from /home/milan/git/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

use crate::{PropertyFlags, PropertyType, ffi};
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct PropertiesRegistry(Boxed<ffi::VtePropertiesRegistry>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::vte_properties_registry_get_type(), ptr as *mut _) as *mut ffi::VtePropertiesRegistry,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::vte_properties_registry_get_type(), ptr as *mut _),
        type_ => || ffi::vte_properties_registry_get_type(),
    }
}

impl PropertiesRegistry {
    #[doc(alias = "vte_properties_registry_get_properties")]
    #[doc(alias = "get_properties")]
    pub fn properties(&self) -> Vec<glib::GString> {
        unsafe {
            let mut length = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_container_num(
                ffi::vte_properties_registry_get_properties(
                    self.to_glib_none().0,
                    length.as_mut_ptr(),
                ),
                length.assume_init() as _,
            );
            ret
        }
    }

    #[doc(alias = "vte_properties_registry_query")]
    pub fn query(&self, name: &str) -> Option<(glib::GString, i32, PropertyType, PropertyFlags)> {
        unsafe {
            let mut resolved_name = std::ptr::null();
            let mut prop = std::mem::MaybeUninit::uninit();
            let mut type_ = std::mem::MaybeUninit::uninit();
            let mut flags = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_registry_query(
                self.to_glib_none().0,
                name.to_glib_none().0,
                &mut resolved_name,
                prop.as_mut_ptr(),
                type_.as_mut_ptr(),
                flags.as_mut_ptr(),
            ));
            if ret {
                Some((
                    from_glib_none(resolved_name),
                    prop.assume_init(),
                    from_glib(type_.assume_init()),
                    from_glib(flags.assume_init()),
                ))
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_registry_query_by_id")]
    pub fn query_by_id(&self, prop: i32) -> Option<(glib::GString, PropertyType, PropertyFlags)> {
        unsafe {
            let mut name = std::ptr::null();
            let mut type_ = std::mem::MaybeUninit::uninit();
            let mut flags = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_registry_query_by_id(
                self.to_glib_none().0,
                prop,
                &mut name,
                type_.as_mut_ptr(),
                flags.as_mut_ptr(),
            ));
            if ret {
                Some((
                    from_glib_none(name),
                    from_glib(type_.assume_init()),
                    from_glib(flags.assume_init()),
                ))
            } else {
                None
            }
        }
    }
}
