// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/milan/git/zoha-vte-rs/gir-files
// from /home/milan/git/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

use crate::{PropertiesRegistry, Uuid, ffi};
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Properties(Boxed<ffi::VteProperties>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::vte_properties_get_type(), ptr as *mut _) as *mut ffi::VteProperties,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::vte_properties_get_type(), ptr as *mut _),
        type_ => || ffi::vte_properties_get_type(),
    }
}

impl Properties {
    #[doc(alias = "vte_properties_dup_property_string")]
    pub fn dup_property_string(&self, prop: &str) -> (Option<glib::GString>, usize) {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = from_glib_full(ffi::vte_properties_dup_property_string(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                size.as_mut_ptr(),
            ));
            (ret, size.assume_init())
        }
    }

    #[doc(alias = "vte_properties_dup_property_string_by_id")]
    pub fn dup_property_string_by_id(&self, prop: i32) -> (Option<glib::GString>, usize) {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = from_glib_full(ffi::vte_properties_dup_property_string_by_id(
                self.to_glib_none().0,
                prop,
                size.as_mut_ptr(),
            ));
            (ret, size.assume_init())
        }
    }

    #[doc(alias = "vte_properties_dup_property_uuid")]
    pub fn dup_property_uuid(&self, prop: &str) -> Option<Uuid> {
        unsafe {
            from_glib_full(ffi::vte_properties_dup_property_uuid(
                self.to_glib_none().0,
                prop.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_properties_dup_property_uuid_by_id")]
    pub fn dup_property_uuid_by_id(&self, prop: i32) -> Option<Uuid> {
        unsafe {
            from_glib_full(ffi::vte_properties_dup_property_uuid_by_id(
                self.to_glib_none().0,
                prop,
            ))
        }
    }

    #[doc(alias = "vte_properties_get_property_bool")]
    #[doc(alias = "get_property_bool")]
    pub fn property_bool(&self, prop: &str) -> Option<bool> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_bool(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(from_glib(valuep.assume_init()))
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_bool_by_id")]
    #[doc(alias = "get_property_bool_by_id")]
    pub fn property_bool_by_id(&self, prop: i32) -> Option<bool> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_bool_by_id(
                self.to_glib_none().0,
                prop,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(from_glib(valuep.assume_init()))
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_data")]
    #[doc(alias = "get_property_data")]
    pub fn property_data(&self, prop: &str) -> Vec<u8> {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_none_num(
                ffi::vte_properties_get_property_data(
                    self.to_glib_none().0,
                    prop.to_glib_none().0,
                    size.as_mut_ptr(),
                ),
                size.assume_init() as _,
            );
            ret
        }
    }

    #[doc(alias = "vte_properties_get_property_data_by_id")]
    #[doc(alias = "get_property_data_by_id")]
    pub fn property_data_by_id(&self, prop: i32) -> Vec<u8> {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = FromGlibContainer::from_glib_none_num(
                ffi::vte_properties_get_property_data_by_id(
                    self.to_glib_none().0,
                    prop,
                    size.as_mut_ptr(),
                ),
                size.assume_init() as _,
            );
            ret
        }
    }

    #[doc(alias = "vte_properties_get_property_double")]
    #[doc(alias = "get_property_double")]
    pub fn property_double(&self, prop: &str) -> Option<f64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_double(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_double_by_id")]
    #[doc(alias = "get_property_double_by_id")]
    pub fn property_double_by_id(&self, prop: i32) -> Option<f64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_double_by_id(
                self.to_glib_none().0,
                prop,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_enum")]
    #[doc(alias = "get_property_enum")]
    pub fn property_enum(&self, prop: &str, gtype: glib::types::Type) -> Option<i64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_enum(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                gtype.into_glib(),
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_enum_by_id")]
    #[doc(alias = "get_property_enum_by_id")]
    pub fn property_enum_by_id(&self, prop: i32, gtype: glib::types::Type) -> Option<i64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_enum_by_id(
                self.to_glib_none().0,
                prop,
                gtype.into_glib(),
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_flags")]
    #[doc(alias = "get_property_flags")]
    pub fn property_flags(
        &self,
        prop: &str,
        gtype: glib::types::Type,
        ignore_unknown_flags: bool,
    ) -> Option<u64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_flags(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                gtype.into_glib(),
                ignore_unknown_flags.into_glib(),
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_flags_by_id")]
    #[doc(alias = "get_property_flags_by_id")]
    pub fn property_flags_by_id(
        &self,
        prop: i32,
        gtype: glib::types::Type,
        ignore_unknown_flags: bool,
    ) -> Option<u64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_flags_by_id(
                self.to_glib_none().0,
                prop,
                gtype.into_glib(),
                ignore_unknown_flags.into_glib(),
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_int")]
    #[doc(alias = "get_property_int")]
    pub fn property_int(&self, prop: &str) -> Option<i64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_int(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_int_by_id")]
    #[doc(alias = "get_property_int_by_id")]
    pub fn property_int_by_id(&self, prop: i32) -> Option<i64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_int_by_id(
                self.to_glib_none().0,
                prop,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_rgba")]
    #[doc(alias = "get_property_rgba")]
    pub fn property_rgba(&self, prop: &str) -> Option<gdk::RGBA> {
        unsafe {
            let mut color = gdk::RGBA::uninitialized();
            let ret = from_glib(ffi::vte_properties_get_property_rgba(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                color.to_glib_none_mut().0,
            ));
            if ret { Some(color) } else { None }
        }
    }

    #[doc(alias = "vte_properties_get_property_rgba_by_id")]
    #[doc(alias = "get_property_rgba_by_id")]
    pub fn property_rgba_by_id(&self, prop: i32) -> Option<gdk::RGBA> {
        unsafe {
            let mut color = gdk::RGBA::uninitialized();
            let ret = from_glib(ffi::vte_properties_get_property_rgba_by_id(
                self.to_glib_none().0,
                prop,
                color.to_glib_none_mut().0,
            ));
            if ret { Some(color) } else { None }
        }
    }

    #[doc(alias = "vte_properties_get_property_string")]
    #[doc(alias = "get_property_string")]
    pub fn property_string(&self, prop: &str) -> (Option<glib::GString>, usize) {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = from_glib_none(ffi::vte_properties_get_property_string(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                size.as_mut_ptr(),
            ));
            (ret, size.assume_init())
        }
    }

    #[doc(alias = "vte_properties_get_property_string_by_id")]
    #[doc(alias = "get_property_string_by_id")]
    pub fn property_string_by_id(&self, prop: i32) -> (Option<glib::GString>, usize) {
        unsafe {
            let mut size = std::mem::MaybeUninit::uninit();
            let ret = from_glib_none(ffi::vte_properties_get_property_string_by_id(
                self.to_glib_none().0,
                prop,
                size.as_mut_ptr(),
            ));
            (ret, size.assume_init())
        }
    }

    #[doc(alias = "vte_properties_get_property_uint")]
    #[doc(alias = "get_property_uint")]
    pub fn property_uint(&self, prop: &str) -> Option<u64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_uint(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_uint_by_id")]
    #[doc(alias = "get_property_uint_by_id")]
    pub fn property_uint_by_id(&self, prop: i32) -> Option<u64> {
        unsafe {
            let mut valuep = std::mem::MaybeUninit::uninit();
            let ret = from_glib(ffi::vte_properties_get_property_uint_by_id(
                self.to_glib_none().0,
                prop,
                valuep.as_mut_ptr(),
            ));
            if ret {
                Some(valuep.assume_init())
            } else {
                None
            }
        }
    }

    #[doc(alias = "vte_properties_get_property_value")]
    #[doc(alias = "get_property_value")]
    pub fn property_value(&self, prop: &str) -> Option<glib::Value> {
        unsafe {
            let mut gvalue = glib::Value::uninitialized();
            let ret = from_glib(ffi::vte_properties_get_property_value(
                self.to_glib_none().0,
                prop.to_glib_none().0,
                gvalue.to_glib_none_mut().0,
            ));
            if ret { Some(gvalue) } else { None }
        }
    }

    #[doc(alias = "vte_properties_get_property_value_by_id")]
    #[doc(alias = "get_property_value_by_id")]
    pub fn property_value_by_id(&self, prop: i32) -> Option<glib::Value> {
        unsafe {
            let mut gvalue = glib::Value::uninitialized();
            let ret = from_glib(ffi::vte_properties_get_property_value_by_id(
                self.to_glib_none().0,
                prop,
                gvalue.to_glib_none_mut().0,
            ));
            if ret { Some(gvalue) } else { None }
        }
    }

    #[doc(alias = "vte_properties_get_registry")]
    #[doc(alias = "get_registry")]
    pub fn registry(&self) -> Option<PropertiesRegistry> {
        unsafe { from_glib_none(ffi::vte_properties_get_registry(self.to_glib_none().0)) }
    }

    #[doc(alias = "vte_properties_ref_property_data_bytes")]
    pub fn ref_property_data_bytes(&self, prop: &str) -> Option<glib::Bytes> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_data_bytes(
                self.to_glib_none().0,
                prop.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_data_bytes_by_id")]
    pub fn ref_property_data_bytes_by_id(&self, prop: i32) -> Option<glib::Bytes> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_data_bytes_by_id(
                self.to_glib_none().0,
                prop,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_image_pixbuf")]
    pub fn ref_property_image_pixbuf(&self, prop: &str) -> Option<gdk_pixbuf::Pixbuf> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_image_pixbuf(
                self.to_glib_none().0,
                prop.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_image_pixbuf_by_id")]
    pub fn ref_property_image_pixbuf_by_id(&self, prop: i32) -> Option<gdk_pixbuf::Pixbuf> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_image_pixbuf_by_id(
                self.to_glib_none().0,
                prop,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_image_surface")]
    pub fn ref_property_image_surface(&self, prop: &str) -> Option<cairo::Surface> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_image_surface(
                self.to_glib_none().0,
                prop.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_image_surface_by_id")]
    pub fn ref_property_image_surface_by_id(&self, prop: i32) -> Option<cairo::Surface> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_image_surface_by_id(
                self.to_glib_none().0,
                prop,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_variant")]
    pub fn ref_property_variant(&self, prop: &str) -> Option<glib::Variant> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_variant(
                self.to_glib_none().0,
                prop.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_properties_ref_property_variant_by_id")]
    pub fn ref_property_variant_by_id(&self, prop: i32) -> Option<glib::Variant> {
        unsafe {
            from_glib_full(ffi::vte_properties_ref_property_variant_by_id(
                self.to_glib_none().0,
                prop,
            ))
        }
    }
}
