// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/milan/git/zoha-vte-rs/gir-files
// from /home/milan/git/zoha-vte-rs/vte/share/gir-1.0
// DO NOT EDIT

use crate::{UuidFormat, ffi};
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialOrd, Ord, Hash)]
    pub struct Uuid(Boxed<ffi::VteUuid>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::vte_uuid_get_type(), ptr as *mut _) as *mut ffi::VteUuid,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::vte_uuid_get_type(), ptr as *mut _),
        type_ => || ffi::vte_uuid_get_type(),
    }
}

impl Uuid {
    #[doc(alias = "vte_uuid_new_from_string")]
    #[doc(alias = "new_from_string")]
    pub fn from_string(str: &str, fmt: UuidFormat) -> Option<Uuid> {
        let len = str.len() as _;
        unsafe {
            from_glib_full(ffi::vte_uuid_new_from_string(
                str.to_glib_none().0,
                len,
                fmt.into_glib(),
            ))
        }
    }

    #[doc(alias = "vte_uuid_new_v4")]
    pub fn new_v4() -> Uuid {
        unsafe { from_glib_full(ffi::vte_uuid_new_v4()) }
    }

    #[doc(alias = "vte_uuid_dup")]
    #[must_use]
    pub fn dup(&self) -> Option<Uuid> {
        unsafe { from_glib_full(ffi::vte_uuid_dup(self.to_glib_none().0)) }
    }

    #[doc(alias = "vte_uuid_equal")]
    fn equal(&self, other: &Uuid) -> bool {
        unsafe {
            from_glib(ffi::vte_uuid_equal(
                self.to_glib_none().0,
                other.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "vte_uuid_free_to_string")]
    pub fn free_to_string(self, fmt: UuidFormat, len: usize) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::vte_uuid_free_to_string(
                self.into_glib_ptr(),
                fmt.into_glib(),
                std::ptr::null_mut(),
            ))
        }
    }

    #[doc(alias = "vte_uuid_new_v5")]
    #[must_use]
    pub fn new_v5(&self, data: &str) -> Option<Uuid> {
        let len = data.len() as _;
        unsafe {
            from_glib_full(ffi::vte_uuid_new_v5(
                self.to_glib_none().0,
                data.to_glib_none().0,
                len,
            ))
        }
    }

    #[doc(alias = "vte_uuid_to_string")]
    pub fn to_string(&self, fmt: UuidFormat) -> (glib::GString, usize) {
        unsafe {
            let mut len = std::mem::MaybeUninit::uninit();
            let ret = from_glib_full(ffi::vte_uuid_to_string(
                self.to_glib_none().0,
                fmt.into_glib(),
                len.as_mut_ptr(),
            ));
            (ret, len.assume_init())
        }
    }

    #[doc(alias = "vte_uuid_validate_string")]
    pub fn validate_string(str: &str, fmt: UuidFormat) -> bool {
        let len = str.len() as _;
        unsafe {
            from_glib(ffi::vte_uuid_validate_string(
                str.to_glib_none().0,
                len,
                fmt.into_glib(),
            ))
        }
    }
}

impl PartialEq for Uuid {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.equal(other)
    }
}

impl Eq for Uuid {}
